[project]
name = "codeanalysis"
version = "1.0.0"
description = "Power up your crews with codeanalysis"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.120.1"
]

[tool.crewai]
type = "tool"
